default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: boilerplate_development

test:
  <<: *default
  database: boilerplate_test

production:
  <<: *default
  database: boilerplate_production
